### ISSUE TITLE
Timepicker: Dropdown items are not horizontally centered

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#667] opened 2017-08-10 11:57 UTC
<img width="236" alt="screen shot 2017-08-10 at 14 55 34" src="https://user-images.githubusercontent.com/1118895/29169314-22eb4708-7ddc-11e7-90c9-28f194526777.png">

**Comment by inikolova** [comment] 2017-08-15 11:22
@yordanov, I tested the TimePicker component in all major browsers, however I am not able to reproduce the issue. Could you please provide more details - which browser have you tested in, which example have you used? Thank you in advance :)

**Comment by siyka-marinova** [comment] 2017-08-24 10:36
Fixed in `@progress/kendo-theme-default@2.40.2`

**Closed as completed by siyka-marinova** 2017-08-24 10:36 UTC
Labels: bug, Appearance, C:Autocomplete, Passed-QA
