### ISSUE TITLE
[Splitter] - Non-resizable, non-collapsable splitters are resizable with keyboard

### ISSUE THREAD

**Issue by IanMuirhead** [telerik/kendo-theme-default#829] opened 2017-12-18 17:53 UTC
## Steps to reproduce
* click inside splitter demo on: https://www.telerik.com/kendo-angular-ui/components/layout/splitter/
* tab from inside the splitter from a resizable pane until you have the top, non-resizable pane selected
* resize with directional keys

![original-state](https://user-images.githubusercontent.com/884395/34120060-36812838-e3d9-11e7-8991-de820424c0d0.png)
![resized-pane](https://user-images.githubusercontent.com/884395/34120059-366af810-e3d9-11e7-93ea-be9444b04250.png)

**Comment by gyoshev** [comment] 2018-02-06 16:20
@IanMuirhead thanks for reporting this, and sorry for the late reply. I'll post an update here when the issue has been addressed.

For the record, since this is an issue with the Angular splitter component, a more appropriate repository to report this is [telerik/kendo-angular](https://github.com/telerik/kendo-angular/issues/).

**Comment by gyoshev** [comment] 2018-02-16 08:51
The issue is [fixed in the development release](https://www.telerik.com/kendo-angular-ui-develop/components/layout/splitter/) and will soon be officially released.

**Closed as completed by gyoshev** 2018-02-16 08:51 UTC
