### ISSUE TITLE
Scheduler: clipped date in month view

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#387] opened 2017-04-11 14:37 UTC
![image](https://cloud.githubusercontent.com/assets/90405/24914615/6755da7e-1edd-11e7-852c-f765619f0f10.png)

**Comment by mparvanov** [comment] 2017-11-13 12:38
Duplicate of https://github.com/telerik/kendo/issues/6769

**Closed as completed** 2017-11-13 12:38 UTC
Labels: bug, SEV: High, C:Scheduler
