### ISSUE TITLE
Items overflow the dropdown wrapper in DropDown widget with serverFiltering

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#406] opened 2017-04-24 13:46 UTC
### Bug report

Items height exceeds the dropdown height in DropDown widget with serverFiltering enabled

### Current behavior
![image](https://cloud.githubusercontent.com/assets/7202037/25340043/2e15b84e-290d-11e7-8259-691f22f145f3.png)

### Expected/desired behavior
Items height doesn't exceed the dropdown height

Note: The issue is reproducible for both default and bootstrap theme.

**Comment by joneff** [comment] 2017-05-02 11:27
The issue is related to kendo UI core rather than the theme. The fix will be available after the referenced PR is merged

**Closed as completed** 2017-05-03 11:17 UTC
Labels: bug, SEV: High, C:Dropdownlist
