### ISSUE TITLE
Make the Grid Pager responsive

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#507] opened 2017-05-19 07:40 UTC
Currently the Grid Pager is lacking its responsive features, available in the Kendo UI for jQuery themes:
[http://plnkr.co/edit/h1rq0B4nb3VhzYf5STAU?p=preview](http://plnkr.co/edit/h1rq0B4nb3VhzYf5STAU?p=preview)

Beyond a certain point of narrowing the Grid width, the next/last page, the ellipsis, and the page number buttons start to disappear.

**Comment by gyoshev** [comment] 2017-05-19 13:56
We need to implement this behind a class name e.g. (`k-grid-responsive-pager`) and render the class in the jQuery suite. This is required as the responsive pager in Angular will show in a different way and may have different rendering.

**Comment by nm-a** [comment] 2018-05-11 13:24
any tentative plan for this?

thank you

**Comment by joneff** [comment] 2018-09-28 12:27
Duplicate of https://github.com/telerik/kendo-themes/issues/121. Please follow the discussion there.

**Closed as completed by joneff** 2018-09-28 12:27 UTC
Labels: duplicate, enhancement, C: Grid, C:Pager
