### ISSUE TITLE
Multiselect input has wrong width when an item is preselected and then deselected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#531] opened 2017-06-06 14:00 UTC
When the selected items list is not empty, and the preselected item is cleared, the input is not sized correctly and cuts of part of the placeholder:

[http://plnkr.co/edit/hENxYYk5c1hzNmHpx6XT?p=preview](http://plnkr.co/edit/hENxYYk5c1hzNmHpx6XT?p=preview)

When there are no preselected values, or values are manually selected and deselected, the component behaves as expected.

**Comment by inikolova** [comment] 2017-06-07 08:01
After further investigation, it appears that the issue is not related to the theme - this problem can be observed only in case the MultiSelect value is set via the value property (if ngModel is used the input size is properly calculated). I am closing the styling issue and opening a new one in the corresponding private repo

**Closed as completed by inikolova** 2017-06-07 08:01 UTC
Labels: bug, SEV: Low, C:Multiselect
