### ISSUE TITLE
k-sorted class incorrectly applied in Grid when a column is hidden before sorting

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-theme-default#676] opened 2017-08-16 11:16 UTC
If you hide a column in the Grid and then sort another (not last) column, the k-sorted class is applied to the cells of the column on the right of the sorted one.
Open this Dojo and follow the instructions:
[Dojo](http://dojo.telerik.com/@tsveti/uqAROM)
You will see that the sorted styling is applied to the Freight column instead of the ShipCity one.

**Note:** The issue is applicable to both the default-v2 and bootstrap-v4 themes.

**Comment by hsuanhan** [comment] 2017-11-27 16:34
I'm having this issue in my application as well. Any update on when this will be resolved?

**Comment by savarex** [comment] 2017-11-30 12:09
hi guys
any news about it?

I'm waiting for a fix too
also kendo.2017.3.1026 is affected

**Comment by kdikov82** [comment] 2017-12-01 06:03
Temporary workaround:
[http://dojo.telerik.com/UjUBe/5](http://dojo.telerik.com/UjUBe/5)

**Comment by joneff** [comment] 2018-04-05 14:27
The issue is not related to the themes. It's related to the KendoUI Grid components. I've transferred the issue in the public KendoUI repository -- https://github.com/telerik/kendo-ui-core/issues/4138

**Closed as completed by joneff** 2018-04-05 14:27 UTC
Labels: invalid
