### ISSUE TITLE
Dialog actions not aligned

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#158] opened 2017-01-23 06:34 UTC
See the Basic Usage demo:

http://www.telerik.com/kendo-angular-ui/components/dialog/

**Comment by KirilNN** [comment] 2017-01-23 15:03
<img width="729" alt="screen shot 2017-01-23 at 4 57 55 pm" src="https://cloud.githubusercontent.com/assets/4188451/22209060/ca86f3f4-e18d-11e6-9fd2-76692d1760c8.png">

Reproduced in Safari on Mac

**Comment by billyjacobs2014** [comment] 2017-01-23 23:18
![image](https://cloud.githubusercontent.com/assets/8147585/22227271/1a0901cc-e190-11e6-90c5-336e9de93807.png)
I reported this bug but the description and location baffles me. The problem is that the content does not display in IE. The height of the window is the title bar + footer and about an inch for the content. What is the estimate of time for the fix. Can I get a hot fix prior to push? This widget worked correctly prior to RCO.

**Comment by gyoshev** [comment] 2017-01-24 10:01
@billyjacobs2014 the issue you are describing should be fixed shortly. It is different than the issue described in this issue, in terms of both the browser and the problem. It is logged in telerik/kendo-angular#192. For a quick workaround, set these styles:

      .k-dialog .k-window-content {
        -ms-flex: none;
        flex: none;
      }

See [this plunkr](http://plnkr.co/edit/txlNgrgMk8cyGCSLvm4a?p=preview).

**Comment by joneff** [comment] 2017-02-19 15:36
@KirilNN @gyoshev the issue is related to using `button` element. For some reason, safari will not respect flexbox and button elements.

Looking back, I remeber @theOrlin has brought this issue up some time ago. The solution was to have an inner span in the buttons that has the styles, or simply not to use `button` element for this particular case.

Also, according to a SO thread (http://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-element-in-some-browsers) , in some browsers `fieldset` and `legend` are not susceptible to flex. We might consider using `span` elements in those cases, should we hit the limitation.

**Comment by gyoshev** [comment] 2017-02-24 16:14
@joneff the workaround [suggested in this post](http://stackoverflow.com/a/40483475/25427) seems to be working in Safari and Firefox

**Closed as completed** 2017-04-10 15:29 UTC
Labels: bug, C:Dialog
