### ISSUE TITLE
<kendo-sortable> element has a default  display:inline

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-theme-default#511] opened 2017-05-22 09:54 UTC
### Description
The `<kendo-sortable>` renders with default `display:inline` style, which breaks the layout in IE11.

### Reproduction
1. Run demo in IE11 - http://plnkr.co/edit/K4b13Qz23s04pzYW0HyK?p=preview
1. Toggle the popup
1. Notice the top padding

### Solution
Make the sortable element `block`.
```
styles: [`
  kendo-sortable {
    display: block;
  }
`]
```

Reported in 1110177

**Comment by gyoshev** [comment] 2017-05-30 12:24
The sortable does not render a `k-widget` (that usually adds `display: block`), because it does not need the borders introduced by the k-widget. I've introduced a `k-display-block` class that we already use in the grid, so that we can trigger this for the sortable, too.

**Comment by tsvetomir** [comment] 2017-06-09 10:33
Note that the Sortable items are wrapped on new lines in develop 
![image](https://user-images.githubusercontent.com/247917/26971959-303f3a8a-4d18-11e7-9f46-16ff1ad25752.png)

**Comment by gyoshev** [comment] 2017-06-12 07:14
Hm, not good. The issue is caused because the Kendo theme is loaded after Bootstrap, and the sortable styles  override the `display: flex` styling from the `.row` class. This can be resolved by applying the default display through the tag, as much as this ties it to the angular implementation.

**Closed as completed** 2017-06-19 10:45 UTC
Labels: bug
