### ISSUE TITLE
Loading indicator missing in latest Chrome

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-theme-default#738] opened 2017-09-27 08:07 UTC
With the latest version of Chrome 61.0.3163.100 (64-bit). The loading icon is no longer visible.

Just open [http://www.telerik.com/kendo-angular-ui/components/styling/icons/#](http://www.telerik.com/kendo-angular-ui/components/styling/icons/) (Unfortunately the plunker function does not work, but just open the example and you can see that any loading icons which is 16px no longer shows. 
17px will however, so seems like a size mismatch calculation.

**Comment by gyoshev** [comment] 2017-10-12 07:09
@Zaixu Thank you for reporting this. It appears that the issue is caused by a rounding error, given that the border-width is set through `em` units.

Until this is fixed, you can workaround it with the following styles:

    .k-i-loading:after, .k-i-loading:before {
        border-width: 0.05em;
    }

**Comment by gyoshev** [comment] 2017-10-31 16:32
Appears to be fixed in `v2.43.2`

**Closed as completed by gyoshev** 2017-10-31 16:32 UTC
Labels: bug, Passed-QA
