### ISSUE TITLE
MaskedTextBox styles are missing

### ISSUE THREAD

**Issue by h22a** [telerik/kendo-theme-default#70] opened 2017-01-06 11:23 UTC
MaskedTextBox for Angular

@joneff

**Comment by gyoshev** [comment] 2017-01-12 11:51
Seems like this was addressed by fb2f9a79db97b83, can either @h22a or @joneff confirm?

**Comment by joneff** [comment] 2017-01-12 12:12
Yes. The issue is resolved. Closing

**Closed as completed by joneff** 2017-01-12 12:12 UTC
Labels: bug, C:Maskedtextbox
